### ISSUE TITLE
Meaning of E512 unclear

### ISSUE THREAD

**Issue by theknut** [ioBroker/ioBroker.repochecker#149]
Whenever I check my repository I get `[E512] "admin/jsonCustom.json5" not found, but custom support is declared` as an error message. The meaning of the message is not documented. Looking at the code it looks like it checks if one of `jsonCustom.json` or `jsonCustom.json5` exists in the `admin`directory.

https://github.com/ioBroker/ioBroker.repochecker/blob/05d574c7b1838a41beefd6eaf03c1f97cdbaf12c/index.js#L1567-L1577

I have a  `jsonCustom.json` file [in my repository](https://github.com/theknut/ioBroker.json-expand/blob/main/admin/jsonCustom.json) and I also configured it in my `io-package.json`

https://github.com/theknut/ioBroker.json-expand/blob/a1520314efe2bef13216936968b12a862b031a6c/io-package.json#L62-L65
```
"adminUI": {
    "config": "none",
    "custom": "json"
},
```

Why am I still getting this error? The custom settings load without errors when I test the adapter.
Furthermore, if I convert my config to `json5` and then delete the other, I get a parsing error when opening the custom options.

**Comment by mcm1957** [comment]
The problem is caused by inconstitent declarations. noCOnfig vs. jsonCustom:json 

But error is no longer issued with checker 0.2.2
