### ISSUE TITLE
`common.mode = subscribe` will be removed with next controller

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.repochecker#164]
According to our research no adapter is currently affected, but should no longer be considered as `ok`
Also the attribute `common.wakeup` is removed in this step, I think a handful of messaging adapters still have this, but it was not needed for a long time now, but likely is not checked here.

https://github.com/ioBroker/ioBroker.js-controller/pull/2634

**Comment by mcm1957** [comment]
ok I'll add

disallow common.mode = subscribe
disallow common.wakeup

**Comment by mcm1957** [comment]
fixed at least with 2.3.0
