### ISSUE TITLE
Automatically close issues if the bugs have been resolved

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.repochecker#19]
This
![grafik](https://user-images.githubusercontent.com/17641229/66744365-88346000-ee7c-11e9-9dec-02ea16666163.png)
should also close the issue IMO

**Comment by GermanBluefox** [comment]
@ldittmar81 Can you do that?

**Comment by mcm1957** [comment]
Implemented with iobroker-bot now
