### ISSUE TITLE
In addition to travis.org, please also check travis.com

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.repochecker#25]
They are now using both travis.org and travis.com, and issues are being created incorrectly because of this.

**Comment by Grizzelbee** [comment]
Just received a Mail from Travis-ci, saying that travis-ci.org will be closed in a couple of month and anything (each and every project) will be migrated to travis-ci.com.

**Comment by Apollon77** [comment]
... but right now we still need to chek both. Currently we have false positive errors
