### ISSUE TITLE
[E605] No actual year found in copyright.  - false positives

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.repochecker#269]
Looks like spaces aroiund years cause false postives.

```Copyright (c) 2021 - 2024 simatec```

https://github.com/simatec/ioBroker.uv-protect/issues/254#issuecomment-2278730126
https://github.com/simatec/ioBroker.uv-protect

@simatec FYI

**Comment by simatec** [comment]
I think that should be corrected in the checker. I don't see any problem with the spelling here.

**Comment by mcm1957** [comment]
Yes, thats this issue for :-).

**Comment by mcm1957** [comment]
fixed with 2.9.1
