### ISSUE TITLE
Do not allow `@iobroker/plugin-sentry` as a adapter dependency

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.repochecker#301]
Adapters should not specify  `@iobroker/plugin-sentry` as production dependency. Also dev dep should not be needed to be honest, however that would not hurt anyone. 

E.g. this is not allowed - https://github.com/Grizzelbee/ioBroker.wireguard/blob/3539747ca6d9be032af00a9820b071c3a10d2ddd/package.json#L24

If this is specified it should be reported as an error and needs a fix before going to stable.

**Comment by mcm1957** [comment]
added 3.1.0
