### ISSUE TITLE
cross origin error

### ISSUE THREAD

**Issue by SVallant** [ioBroker/ioBroker.repochecker#31]
when testing with https://github.com/minukodu/ioBroker.minuvis i got an empty output but error in console:
`
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://3jjxddo33l.execute-api.eu-west-1.amazonaws.com/defau…r?url=https%3A%2F%2Fgithub.com%2Fminukodu%2FioBroker.minuvis. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).`

**Comment by GermanBluefox** [comment]
Done
