### ISSUE TITLE
Please disable/change check for additional languages - [E506] More non translated in german or russian words found

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.repochecker#37]
Hi,

The following error message occurs if just English and a second language (in my case German) is in words.js. 
`[E506] More non translated in german or russian words found in admin/words.js. You can use https://translator.iobroker.in/ for translations`

Please see very current forum discussions:
* https://forum.iobroker.net/topic/36660/trial-weblate-f%C3%BCr-iobroker-%C3%BCbersetzungen/21
* https://forum.iobroker.net/post/489405

Current and latest community ~~consensus~~ discussion is to have English as a must, plus a second language (German), but to **not** use automatic translations, since these are usually pretty poor (e.g. Table column -> German: "Säule" - Germans would not understand what "Säule" means related to ioBroker settings).
Also, automated translations can be pretty offending if words are translated faulty and/or brought into the wrong context. The www is certainly full of many examples.

Therefore, can we please disable this check.  

Many thanks.

**Comment by Apollon77** [comment]
> Current and latest community consensus 

Sorry but where we decided that?

**Comment by Mic-M** [comment]
Hi Ingo,
Apologies, I was typing too fast in the initial issue description, that was a long day for me;-) No consensus/decision, but discussion, I corrected above. Also, I did not review repochecker's index.js while opening this issue.

Anyway, per repochecker's index.js ([line link](https://github.com/ioBroker/ioBroker.repochecker/blob/c0a29626d981041124e474009b13abac395c54c0/index.js#L1221)): if `words.js`  contains >3 items without "de" or "ru" translations, [E506] is thrown. 

This implies that we have 3 mandatory languages in ioBroker: **English, German, Russian**. https://www.iobroker.net/#de/statistics confirms that Russia is following German-speaking countries in the top countries list.

However, for me as developer it is impossible to review automated translations like into ru, which can be pretty horrible translated. Especially if it comes to adapter settings fields, this is critical for usability, especially with rather complex adapter settings including many tables, option tabs etc., like SmartControl, iQontrol, and so on. If the adapter documentation is in English (and German) only, field names are not matching, confusing, etc., users have no clue about what means what, etc.
To me, it makes way much sense to allow excluding certain languages and always having English as fallback (and the fallback to English is already built into ioBroker and very well working).

Thanks

**Comment by GermanBluefox** [comment]
> However, for me as developer it is impossible to review automated translations like into ru, which can be pretty horrible translated.

I can and will check it. 
And believe me: it is much easier for me to edit almost "ready to use" text with a couple of wrong translations, than to create a file anew and copy all the stuff inside it.

**Comment by GermanBluefox** [comment]
Please show me an adapters, so I can check it (or delegate it to russian users).

**Comment by Mic-M** [comment]
Many thanks @GermanBluefox -- my rather complex adapter regarding configuration and requiring Russian translation review is [**Smart Control**](https://github.com/Mic-M/ioBroker.smartcontrol). Appreciate your help!

_By the way and just as a note_:
The Smart Control adapter documentation is being embedded within `admin/index_m.html` from the files in [admin/doc-md](https://github.com/Mic-M/ioBroker.smartcontrol/tree/master/admin/doc-md) by using [zero-md module](https://github.com/zerodevx/zero-md). Currently, I am translating just German and English, but no concerns here regarding limiting to these languages, since even extremely popular adapters like Homematic do not provide the adapter documentation in all 10 languages. Anyway:  if a user does not have set EN or DE within the ioBroker configuration, English will be embedded as the fallback, and a note included to ask for translation contribution ;-) - see dark blue text in the screenshot below:
![image](https://user-images.githubusercontent.com/39859059/93719957-3dd85a80-fb86-11ea-82a2-9300bba59eac.png)

Current snapshot from [admin/index_m.js](https://github.com/Mic-M/ioBroker.smartcontrol/blob/master/admin/index_m.js):
```javascript
    /**
     * Apply markdown for documentation through https://github.com/zerodevx/zero-md
     */

    // index_m.html: All ids defined in <zero-md> tags, like ['md-start', 'md-targetDevices', ...]
    const mdIds = $('zero-md[manual-render]').map((i, el) => el.getAttribute('id')).get(); // https://stackoverflow.com/a/54392415
    for (const mdId of mdIds) {
        getObject('system.config', (error, result)=> {
            if (!error && result && result.common && result.common.language) {
                const lang = result.common.language;
                const mdFilePath = $('zero-md#' + mdId).attr('src'); // like 'doc-md/start_en.md'
                if (mdFilePath) {
                    
                    if (lang !== 'en') { // English is always required
                        const newFilePath = mdFilePath.slice(0, -5) + `${lang}.md`; // remove last 5 chars 'en.js' and add <lang>.js
                        if (fileExists(newFilePath)) {
                            $('zero-md#' + mdId).attr('src', newFilePath); // set new file path src of <zero-md>                      
                        } else {
                            // Fallback is English. We add a note to the HTML
                            $(`
                                <p class='translation-required'>
                                    Your current ioBroker language is <strong>${lang.toUpperCase()}</strong>, however, the following instructions have not yet been translated into your language, so English is used as fallback.
                                    If you are fluently speaking ${lang.toUpperCase()}, please help and translate into your language.
                                    The English file is <a target="_blank" href="https://github.com/Mic-M/ioBroker.smartcontrol/blob/master/admin/${mdFilePath}">located on Github</a>.
                                    Please translate and provide a Github pull request for adding a new file '${newFilePath}' with your ${lang.toUpperCase()} translation. Thank you!
                                </p>
                            `).insertBefore('zero-md#' + mdId);
                        }
                    }
                } else {
                    console.warn(`load(): mdFilePath for '${mdId}' is undefined, so we use English.`);
                }
            } else {
                console.warn('Error while getting ioBroker system configuration language, so we use English.');
            }
            // Finally, render zero-md - https://github.com/zerodevx/zero-md#public-methods
            // We add a slight delay, just in case
            setTimeout(() => {
                const el = document.querySelector('zero-md#' + mdId);
                // @ts-ignore
                el.render();                        
            }, 100);

        });
    }
```
