### ISSUE TITLE
E125 ist nicht verständlich

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.repochecker#4]
https://github.com/ioBroker/ioBroker.repochecker/blob/4e0fc62119abc88127073a70c170d94c86121ed0/index.js#L785

Wie hier zu sehen: https://github.com/ruhigundrelaxed/ioBroker.hyperion/issues/24 -> da steht ja, dass die Datei nicht da ist, aber die Datei ist da - es fehlt nur in der io-package common.extIcon.

**Comment by GermanBluefox** [comment]
Fixed?

**Comment by ldittmar81** [comment]
Wir können denke ich so lassen... er hat halt den www.github.com Link drin gehabt. Ist halt leicht zu übersehen. Ich mache es mal zu :-)
