### ISSUE TITLE
Add check for "common.tier" (added in js-controller 3.3.0)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.repochecker#43]
Feature status: Technology preview (since 3.3.0)

Starting from js-controller 3.3.0 you can define the common.tier attribute in the io-package.json. Lower TIERS will start before higher TIERS. Currently, 3 TIER levels are supported. Note, that the admin adapter as the central control platform will always be started first.

TIER 1

Logic and scripting engines, which should be able to act as fast as possible to work with states delivered by higher TIER adapters.

TIER 2

Adapters which deliver data from external APIs, which are important and can change at any time

TIER 3

Adapters which are not time critical like Visualization, Backup adapters and adapters whose information do not necessarily need to be up-to-date. These are often schedule adapters, whose information is always a bit delayed.

**Comment by Apollon77** [comment]
Check should be that tier, if defined, is 1,2 or 3 ... no value else is allowed

**Comment by GermanBluefox** [comment]
Done
