### ISSUE TITLE
'[E506] "admin/jsonCustom.json" not found, but custom support is declared' - but the file is there

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.repochecker#46]
I get the following error message:
![image](https://user-images.githubusercontent.com/49171332/137888486-cddc4360-448e-4a86-87f5-1eb99412c741.png)

But the file is present, has valid json and works:
![image](https://user-images.githubusercontent.com/49171332/137888743-6a52302c-1367-4e6f-b48a-85442a3ddb68.png)

**Comment by sbormann** [comment]
Hi @GermanBluefox , could you please have a look after that? I can't update stable version because adapter-checker throws an error.

I think this is the line to look at:
https://github.com/ioBroker/ioBroker.repochecker/blob/300585c6e83212f4ab8f771f62734ddb95593e94/index.js#L1368

**Comment by SVallant** [comment]
same problem with rhis repo:
https://github.com/minukodu/ioBroker.minuaru/

**Comment by klein0r** [comment]
Issue was this line (missing admin dir):

https://github.com/ioBroker/ioBroker.repochecker/blob/300585c6e83212f4ab8f771f62734ddb95593e94/index.js#L1277

Will be fixed with #52

**Comment by GermanBluefox** [comment]
@SVallant please verify

**Comment by SVallant** [comment]
Working now, good Job !
Thank you

**Comment by sbormann** [comment]
Works perfectly now. Thank you!
