### ISSUE TITLE
[Enhancement] check npm version

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.repochecker#51]
Compare version in package.json and the version on npm. If they do not match show a info or warning.

**Comment by Apollon77** [comment]
YOu mean for stable updates? Then it is more about "given version do not exist on npm", or? Because if could be that already newer version ison npm

**Comment by Jey-Cee** [comment]
Not special for stable updates more in general, that is why i said as **info** or warning. 
But if its possible to define extra checks for stable repository PRs this should drop an error.
"given version do not exist on npm" <- YES that makes sense, as it is possible to check against a branch.
