### ISSUE TITLE
Auto-Update for Amazon AWS (from repo)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.repochecker#53]
- https://www.iobroker.dev/adapter-check and
- https://adapter-check.iobroker.in

are using ``https://3jjxddo33l.execute-api.eu-west-1.amazonaws.com/default/checkAdapter`` to run the checks. At the moment the version on the server differs from the master branch (which is a bit confusing).

e.g. ``[W801] .npmignore not found`` is returned, which has been fixed 7 month ago in 300585c6e83212f4ab8f771f62734ddb95593e94

https://github.com/ioBroker/ioBroker.repochecker/blob/300585c6e83212f4ab8f771f62734ddb95593e94/index.js#L1544-L1546

**Comment by GermanBluefox** [comment]
Updated
