### ISSUE TITLE
Error "Bluefox was not found in the collaborators on NPM!

### ISSUE THREAD

**Issue by SKB-CGN** [ioBroker/ioBroker.repochecker#63]
Hi,
while running this as cli, the App shows the above error, but bluefox is added in NPM as you can see here:

![2022-07-06 08_10_28-iobroker wallbox - npm — Mozilla Firefox](https://user-images.githubusercontent.com/58603329/177480933-e82fa37d-7984-4519-a071-097339ca0c4d.png)

**Comment by GermanBluefox** [comment]
Which adapter is that?

**Comment by SKB-CGN** [comment]
It's https://github.com/SKB-CGN/ioBroker.energiefluss

**Comment by Apollon77** [comment]
Please try again ... does ist work today?
