### ISSUE TITLE
[E201] Bluefox was not found

### ISSUE THREAD

**Issue by raschy** [ioBroker/ioBroker.repochecker#66]
When trying to bring an adapter into the last repository I get the error "[E201] Bluefox was not found in the collaborators on NPM!". 
But Bluefox is added! This happened when adding https://github.com/raschy/ioBroker.solarmanpv.
 Is this a issue or is there anything else I can do?

**Comment by GermanBluefox** [comment]
I retested just now and `bluefox` was found..

**Comment by raschy** [comment]
Ok, what can I do now. Create a new release and hope that it works?

**Comment by Apollon77** [comment]
yes

**Comment by raschy** [comment]
Adapter could be successfully added to the repository. Many thanks.
