### ISSUE TITLE
[W202] Version of package.json (0.0.3) doesn't match latest version on NPM

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.repochecker#67]
When checking adapter https://github.com/ice987987/ioBroker.hagelschutz on https://adapter-check.iobroker.in/ I'll get the error:

`[W202] Version of package.json (0.0.3) doesn't match latest version on NPM ("\n<!doctype html>\n<html lang=\"en\">\n <head>\n <meta charset=\"utf-8\">\n <link rel=\"stylesheet\" href=\"https://static.npmjs.com/styles.14bdc48cd499cbd8c04c.css\" />\n <title data-react-helmet=\"true\">iobroker.hagelschutz - npm</title>\n <meta data-react-helmet=\"true\" http-equiv=\"cleartype\" content=\"on\"/><meta data-react-helmet=\"true\" name=\"apple-mobile-web-app-capable\" content=\"yes\"/><meta data-react-helmet=\"true\" name=\"viewport\" content=\"width=device-width,minimum-scale=1.0,initial-scale=1,user-scalable=yes\"/><meta data-react-helmet=\"true\" property=\"og:image\" content=\"https://static.npmjs.com/338e4905a2684ca96e08c7780fc68412.png\"/><meta data-react-helmet=\"true\" name=\"msapplication-TileColor\" content=\"#cb3837\"/><meta data-react-helmet=\"true\" name=\"msapplication-TileImage\" content=\"https://static.npmjs.com/7a7ffabbd910fc60161bc04f2cee4160.png\"/><meta data-react-helmet=\"true\" name=\"msapplication-config\" (...)`

But: Adapter is available on NPM in the required version.

**Comment by GermanBluefox** [comment]
Fixed

**Comment by ice987987** [comment]
thank you very much, initial issue is solved.

**BUT**:
`Bluefox found in collaborators on NPM / 72` is now ticket as OK, which is not true/correct.

**Comment by Apollon77** [comment]
hat gerade noch jemand einen adapter wo der checker meckert das Bluefox nicht auf npm ist abert er ist es? -->  https://github.com/ioBroker/ioBroker.repochecker/issues/63#issuecomment-1220442922
