### ISSUE TITLE
make ## License check more tolerant (accept bold header too)

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.repochecker#68]
snmp Adapter does not pass the adapter check

[E604] No "## License" found in README.md

The reason is, that this header is bolded (just as all other level 2 headers) within this README.md

    ## __License__

So please consider accepting ## __License__  as well as ## License

The reason to mark the headers bold is that this provides a better readabilty - at least in my oppinion.

**Comment by GermanBluefox** [comment]
There are some hidden features behind Titles in Readme. Documentation page looks exactly for `#+\sLicense/i`.
Please use `## License`
