### ISSUE TITLE
[W156] Adapter should support admin 5 UI (jsonConfig) - misleading when using React

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.repochecker#73]
We shouldn't show this warning when the dev/adapter is actually using a modern UI. I'm not sure what gets checked here, but maybe it only makes sense for true legacy UIs (i.e. index.html, not index_m.html)?

**Comment by Apollon77** [comment]
The question is how to find out if an adapter "just uses a normal index_m.html" or a one with a react UI or such behind it?

I adjusted the log message for now as short workaround

**Comment by mcm1957** [comment]
still open

**Comment by mcm1957** [comment]
see https://github.com/ioBroker/ioBroker.repochecker/issues/175

**Comment by mcm1957** [comment]
fixed with 2.6.1 (at least as a first try)
