### ISSUE TITLE
lang uk (from new translator) cause "W145"

### ISSUE THREAD

**Issue by oelison** [ioBroker/ioBroker.repochecker#76]
With the new translator the list of languages is expanded with "uk".
The repochecker report this with
[W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)

**Comment by Apollon77** [comment]
Add uk here https://github.com/ioBroker/ioBroker.repochecker/blob/9e9228a62dfc8424fb90dcc633cda22bae235e0d/index.js#L277

**Comment by oelison** [comment]
Should additional languages be ignored or did we want always a fixed list? (not more and not less)

**Comment by Apollon77** [comment]
lets have it maximum for now. will be fixed with next version
