### ISSUE TITLE
Missleading error message for dependencies

### ISSUE THREAD

**Issue by jack-blackson** [ioBroker/ioBroker.repochecker#90]
When adding the dependencies in io-package like, this, you get an error message:

`"dependencies": {
            "js-controller": ">=3.0.0"
        },
`
![image](https://user-images.githubusercontent.com/13975634/211161607-4ccc8526-91aa-48f7-be11-59ec1b9808bd.png)

According to Apollo77, this should be fine. When changing it to an array, it is fine. "Formal ist "dependencies" aber ein "array von objekten und nicht nur ein objekt"

**Comment by mcm1957** [comment]
dependencies and globalDependencies must by of type array (see schema). 
Check has been adapted to putput a clear error message.

**Comment by mcm1957** [comment]
fixed at 2.4.0
