### ISSUE TITLE
[Feature] Check validity of roles specified at io-pacckage.json

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.repochecker#91]
To avoid feedbacck during review due to illegal roles:

> Please do not invent own roles (...). Use the defined list or open an issue in ioBoker repo for new role addition discussion

I would suggest to evaluate whether adapter checker could check the specifiesd roles.

Not top prior, but as adapter checker opens / reads io-package.json anway it should not be much effort to check the values against tha static list of valid roles.

**Comment by Apollon77** [comment]
repo checker will have no chance bevause this would requore a "semantic understanding" of the code

**Comment by mcm1957** [comment]
There seems to be some misunderstanding. The rpochecker does not need to interpret ANY code to check the config inside io-package.json. I (only) suggested to check the roles specified here:

Extract from io-package.jsoen:
```
    "instanceObjects": [
        {
            "_id": "info",
            "type": "channel",
            "common": {
                "name": "Information"
            },
            "native": {}
        },
        {
            "_id": "info.connection",
            "type": "state",
            "common": {
                "name": "is wallbox connected?",
                "type": "boolean",
                "role": "indicator.connected",    <<<<<<<<<<<<<<<<<<
                "read": true,
                "write": false,
                "def": false
            },
            "native": {}
        },
```
