### ISSUE TITLE
common.noConfig is DEPRECATED in admin version >=5 

### ISSUE THREAD

**Issue by xXBJXx** [ioBroker/ioBroker.repochecker#92]
The adapter check gives an error that common.NoConfig and common.adminUI.config = none should be included in the config 
![image](https://user-images.githubusercontent.com/32600934/213938016-8657e080-4750-4437-b822-2d6528c65b9a.png)
but in the JSON schema common.NoConfig in admin version >= 5 is DEPRECATED and you should only use common.adminUI.config = none
![image](https://user-images.githubusercontent.com/32600934/213938041-e02475b2-0ff2-4976-bea3-fcab442e50db.png)
i do the same and the admin is entered as globalDependencies on version >=5
![image](https://user-images.githubusercontent.com/32600934/213938058-85e6c59a-bf54-4476-9af0-e083e7ca7f77.png)
![image](https://user-images.githubusercontent.com/32600934/213938069-288a36b6-7ba2-4199-837d-8532f7e7957a.png)

**Comment by mcm1957** [comment]
still open

**Comment by mcm1957** [comment]
@Apollon77 
Is this information correct? Please confirm.
I could adapt the errortext for sure if the info in this issue is still correct
